theme = "base16_transparent"
[editor]
bufferline = "multiple"
color-modes = true
completion-trigger-len = 1
cursorline = true
idle-timeout = 50
line-number = "relative"
mouse = true
rulers = [80]
scrolloff = 8
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
character = "╎"
render = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.statusline]
center = ["file-name"]
left = ["mode", "spinner", "version-control"]
right = ["workspace-diagnostics", "selections", "position-percentage", "position", "file-encoding", "file-type"]

[editor.whitespace]
[editor.whitespace.character]
tab = "→"
tabpad = "·"

[editor.whitespace.render]
tab = "all"

[keys]
[keys.normal]
A-j = ["ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection", "add_newline_below", "move_line_down", "replace_with_yanked"]
A-k = ["ensure_selections_forward", "extend_to_line_bounds", "extend_char_right", "extend_char_left", "delete_selection", "move_line_up", "add_newline_above", "move_line_up", "replace_with_yanked"]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
Q = ":quit-all!"
q = ":quit"
w = ":write"

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]
